### ISSUE TITLE
Feature request, multi drive scatter

### ISSUE THREAD

**Issue by ltomes** [jbrodriguez/unbalance#49]
I don't see a lot of discussion on this so maybe it's not a high demand feature. 

Feature:
Is a multi drive scatter something that is feasible with the rsync features unbalance uses today? If not would it be appropriate to change the checkbox to a radio button?

(My) use case:
When I use scatter I am normally clearing multiple drives that are aging out.
Scattering one drive at a time is a bit rough since it's a 20+ hour task for 6tb+ drives in my configuration and there's a lot of downtime between drives/it would be awesome to be able to select multiple drives to scatter/do one large action.

Thanks for your time and happy holidays,

**Comment by jbrodriguez** [comment]
Hi thanks for the request ! Happy holidays !

This would complicate the current logic quite a bit, the reason is the code assumes there's one source drive in scatter operations.

It's not likely that I will implement it (PRs are welcome), but if I happen to find some down time in the future, I may look into it.

**Comment by jbrodriguez** [comment]
will not be working on this myself, i will accept a pr though
