### ISSUE TITLE
scatter just copy to one disk when multi target disk selected

### ISSUE THREAD

**Issue by shuosiw** [jbrodriguez/unbalance#52]
I have selected 3 disk as target in scatter. But unbalance just copy the file to the first one.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/2578976/171794494-dc9af225-0b7f-4eb5-8cc6-0f9d9ba21263.png">

I want to balance the file on disk2 to other 3 disks. but found that it just copy to disk3?

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/2578976/171794639-e5e540a6-d70f-49ed-b959-dfb99885e9eb.png">

**Comment by jbrodriguez** [comment]
scatter doesn't distribute data among drives, it fills drives in free space order, so it may not touch a drive that's second or third, i have been unable to come up with a proper name for this feature, so scatter is what still sticks 🤷‍♂️

**Comment by jbrodriguez** [comment]
it seems to me that redistribute conveys the same general idea as scatter, so it doesn't seem to make a difference (to me, english isn't my first language), any thoughts ?

**Comment by DataBitz** [comment]
They are similar but Redistribute to me seems like a more accurate description of how unbalance is operating.
Scatter is spreading out in random directions.
Redistribute is to spread out in controlled portions.
https://comparewords.com/distribute/scatter

**Comment by jbrodriguez** [comment]
didn't know about that page, it starts making sense, i'll run a poll to make the decision, thanks for looking into this

**Comment by shuosiw** [comment]
> scatter doesn't distribute data among drives, it fills drives in free space order, so it may not touch a drive that's second or third, i have been unable to come up with a proper name for this feature, so scatter is what still sticks 🤷‍♂️

I think the better way is to adjust that only one target disk can be selectd. Instead of changing the name

**Comment by jbrodriguez** [comment]
allowing only one target would place an artificial limit on the calculations, it's definitely a controversial subject 🤷‍♂️

**Comment by hot22shot** [comment]
Hi, sorry for the necro as it is an old thread but I came here for the same question as the original poster.
While scatter does indeed fill drives you can actually force it to really "distribute" data by using the reserved space settings.

For example : I am moving 4 To of data from one disk to 5 other disks (with different sizes and free spaces).
By setting the reserved space at 2 To, the scatter algorithm will distribute the data to my 5 other disks instead of filling one (and then the next disk, etc).
Of course I had to test multiple values of the reserved space settings (up to 2 To in my setup) for unbalanced to distribute the data to all my disks.
