### ISSUE TITLE
Feat - Queue multiple jobs

### ISSUE THREAD

**Issue by fishpen0** [jbrodriguez/unbalance#56]
I have 9 disks and am doing scatter and gather operations on hundreds of folders, but not always to the same disk or set of disks.  I can't queue them and walk away for a few days since once a job is running the rest of the UI locks down

**Comment by swshong** [comment]
Yes! I just made a question on the Unraid forum but now I know that this feature is lacking right now. Please consider this!

**Comment by jbrodriguez** [comment]
hi, i will not work on this, mostly because the plan phase (calculate free space required and such) would not work after the first plan, it would be just a guess, you can't know if the current operation will fail, or any other external factor that might have an impact

you can set notifications in the settings, so that you're notified when the operation completes via email, that would allow you to start another plan/operation once the first one finishes, that would be the "workaround" :)
