### ISSUE TITLE
Scatter/Gather with checksum validation

### ISSUE THREAD

**Issue by DanTheMan827** [jbrodriguez/unbalance#58]
So, I was using the gather mode to move a bunch of data to a newly formatted drive, but after moving all the data, I noticed ZFS was saying a bunch of files were corrupt.

I’m not saying this was caused by unbalance, there was an issue elsewhere, a loose cable I think

But the ability for unbalance to read the newly copied data and validate it before deleting the old data would be quite useful.

Forgive me if this is already an option, but I didn’t see it.

**Comment by jbrodriguez** [comment]
unbalance uses rsync underneath, so any validation option has to use rsync in order to work.

rsync has a checksum validation, however, since it requires the original source to be available, unbalance exposes it only for the scatter / copy operation, a validation button shows up for the most recent scatter/copy operation in the history screen
